### PR TITLE
Initial set of go modules

### PR DESCRIPTION
**Pull request by bruth**
I learned that a single git repo can support multiple go modules that can be tagged with independent versions. The link is in the README change, but read [here](https://github.com/go-modules-by-example/index/blob/master/009_submodules/README.md) for a short tutorial.

The other packages in this repo depend on one of the modules in this PR so this will there will be a subsequent PR with those module additions.

@dmead Following out conversation last week about shared libraries, having a monorepo to manage these makes the idea a bit more compelling, since there isn't the overhead of creating a new repo. However we can still propose and evaluate new packages on a case by case basis.

### CODE REVIEW

**Comment by bruth** [comment]
This changes the scope of the *Go module* for this repo. Without this change, `go get` and `go mod` would only acknowledge the root of this repo as the module. This change add `go.mod` to each relevant directory in this repo that should be treated as standalone, fetchable module. The benefit is that each module can be versioned/tagged separately and thus incorporated independently within a project.

**Comment by bruth** [comment]
@murphyke ☝️ Does that make sense and answer your question?

**Comment by murphyke** [comment]
> @murphyke ☝️ Does that make sense and answer your question?

Yes.

**Comment by bruth** [comment]
@dmead Any comments on this?

**Comment by bruth** [comment]
Moving forward with the one approval.

**Comment by dmead** [comment]
sorry for the slow response. i was occupied with other stuff

this seems like a good way to deal with version conflicts. it's way better than what maven makes you do which is re-write conflicting jars with an annoying plugin.

**Comment by bruth** [comment]
No worries, thanks for the confirmation.

**Pull request merged**
